version: 2
jobs:
  build:
    image: docker:18.09.4

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          version: 18.09.3
          docker_layer_caching: true

      - run: docker build .
